baseURL = "https://sasrobotics.xyz"
languageCode = "en-us"
title = "SAS Robotics"
theme = "ananke"

copyright = "©2019 SAS Robotics Team"

paginate = 6
enableRobotsTXT = true
enableGitInfo = true
canonifyURLs = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
    [[menu.main]]
        identifier = "vex"
        name = "VEX"
        title = "Vex Robotics"
        pre = "<img src='/img/vex/logo-circle.png' style='height: 1.5em;display: inline-flex; vertical-align: middle;' />"
        url = "/vex/"
        weight = 1
    [[menu.main]]
        identifier = "mate"
        name = "MATE"
        title = "Marine Advanced Technology Education"
        pre = "<img src='/img/mate/logo-circle.png' style='height: 1.5em;display: inline-flex; vertical-align: middle;' />"
        url = "/mate/"
        weight = 2
    [[menu.main]]
        identifier = "frc"
        name = "FRC"
        title = "FIRST Robotics Competition"
        pre = "<img src='/img/frc/logo-circle.png' style='height: 1.5em;display: inline-flex; vertical-align: middle;' />"
        url = "/frc/"
        weight = 3
    [[menu.main]]
        identifier = "about"
        name = "About Us"
        title = "About Us"
        url = "/about/"
        weight = 4

[params]
    favicon = "nonfree/img/favicon.ico"
    github = "https://github.com/sas-mate-robotics"
    custom_css = ["css/app.css"]
    background_color_class = "bg-dark-gray"
